package com.expensetracker.api.transactions;

import java.math.BigDecimal;
import java.sql.Array;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;

import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import com.expensetracker.api.accounts.AccountService;
import com.expensetracker.api.dedup.DedupService;
import com.expensetracker.api.merchants.MerchantService;

/**
 * Transaction reads and writes.
 *
 * <p>Amounts are stored positive with the sign in {@code direction};
 * {@code signed_amount} is generated by the database so totals are a plain SUM
 * that cannot disagree with the rows it sums.
 */
@Service
public class TransactionService {

    /** Joined so the list view can render names without a second round trip. */
    private static final String SELECT = """
            select t.id, t.kind::text as kind, t.direction::text as direction,
                   t.amount, t.signed_amount, t.currency, t.occurred_at,
                   t.description, t.notes, t.tags,
                   t.account_id, a.name as account_name,
                   t.category_id, c.name as category_name,
                   t.merchant_id, m.name as merchant_name,
                   t.transfer_id,
                   other.account_id as counterpart_account_id,
                   oa.name as counterpart_account_name,
                   t.external_ref, t.merged_into_id,
                   case
                     when t.import_batch_id is not null then 'import'
                     when t.raw_message_id is not null then 'auto'
                     else 'manual'
                   end as source,
                   t.is_excluded, t.is_recurring, t.created_at
            from transactions t
            left join accounts a   on a.id = t.account_id
            left join categories c on c.id = t.category_id
            left join merchants m  on m.id = t.merchant_id
            left join lateral (
                select o.account_id
                from transactions o
                where o.transfer_id = t.transfer_id
                  and o.id <> t.id
                  and t.transfer_id is not null
                limit 1
            ) other on true
            left join accounts oa on oa.id = other.account_id
            """;

    private static final RowMapper<TransactionView> MAPPER = TransactionService::mapRow;

    private final JdbcTemplate jdbc;
    private final AccountService accounts;
    private final MerchantService merchants;
    private final DedupService dedup;

    public TransactionService(JdbcTemplate jdbc, AccountService accounts, MerchantService merchants,
            DedupService dedup) {
        this.jdbc = jdbc;
        this.accounts = accounts;
        this.merchants = merchants;
        this.dedup = dedup;
    }

    public Page list(UUID userId, TransactionFilter filter) {
        TransactionFilter.Compiled compiled = filter.compile(userId);

        // occurred_at then id: without a tiebreaker, rows sharing a timestamp
        // can appear on two pages or on none as the user pages through.
        String sql = SELECT + compiled.where() + " order by t.occurred_at desc, t.id desc limit ? offset ?";
        List<Object> args = new ArrayList<>(compiled.args());
        args.add(filter.limit());
        args.add(filter.offset());

        List<TransactionView> rows = jdbc.query(sql, MAPPER, args.toArray());

        String countSql = """
                select count(*), coalesce(sum(t.signed_amount), 0)
                from transactions t
                left join merchants m on m.id = t.merchant_id
                """ + compiled.where();

        return jdbc.query(countSql, rs -> {
            rs.next();
            return new Page(rows, rs.getLong(1), rs.getBigDecimal(2), filter.limit(), filter.offset());
        }, compiled.argArray());
    }

    public TransactionView get(UUID userId, UUID id) {
        return find(userId, id).orElseThrow(TransactionService::notFound);
    }

    private Optional<TransactionView> find(UUID userId, UUID id) {
        return jdbc.query(SELECT + " where t.user_id = ? and t.id = ? and t.deleted_at is null",
                MAPPER, userId, id).stream().findFirst();
    }

    @Transactional
    public TransactionView create(UUID userId, TransactionRequest request) {
        return create(userId, request, Origin.MANUAL).view();
    }

    @Transactional
    public Created create(UUID userId, TransactionRequest request, UUID importBatchId) {
        return create(userId, request, Origin.csvImport(importBatchId));
    }

    /**
     * Creates a transaction and records where it came from.
     *
     * <p>Origin matters beyond bookkeeping: it tells the dedup policy that two
     * rows came from the same statement (and a statement lists each payment
     * exactly once), or that a row came from a mail alert (which the same
     * payment on a statement should fold into rather than sit beside).
     */
    @Transactional
    public Created create(UUID userId, TransactionRequest request, Origin origin) {
        TransactionKind kind = request.resolvedKind();
        TransactionDirection direction = request.resolvedDirection();

        if (request.accountId() != null) {
            accounts.requireOwned(userId, request.accountId());
        }

        UUID merchantId = merchants.resolve(userId, request.merchant()).orElse(null);
        UUID categoryId = resolveCategory(userId, request.categoryId(), merchantId);

        // A bank reference is proof of identity and the database enforces it as
        // unique, so a second report of one is folded in before the insert is
        // attempted rather than after — otherwise re-importing an overlapping
        // statement would fail outright instead of deduplicating.
        String reference = request.externalRefOrNull();
        if (reference != null) {
            Optional<UUID> existing = dedup.findByReference(userId, reference);
            if (existing.isPresent()) {
                DedupService.Outcome absorbed = dedup.absorb(userId, existing.get(),
                        request.accountId(), categoryId, merchantId, request.description());
                return new Created(get(userId, existing.get()), absorbed);
            }
        }

        UUID id = insert(userId, kind, direction, request, merchantId, categoryId, origin);

        merchants.rememberCategory(userId, merchantId, request.categoryId());

        // If this turned out to be a second report of an existing payment, show
        // the row that survived rather than the one now hidden behind it.
        DedupService.Outcome outcome = dedup.screen(userId, id);
        return new Created(get(userId, outcome.isMerged() ? outcome.survivorId() : id), outcome);
    }

    /** A created transaction plus what deduplication made of it. */
    public record Created(TransactionView view, DedupService.Outcome dedup) {
    }

    private UUID insert(UUID userId, TransactionKind kind, TransactionDirection direction,
            TransactionRequest request, UUID merchantId, UUID categoryId, Origin origin) {
        return jdbc.queryForObject("""
                insert into transactions (
                    user_id, account_id, category_id, merchant_id,
                    kind, direction, amount, currency, base_amount,
                    occurred_at, description, notes, tags,
                    external_ref, is_excluded, is_recurring, import_batch_id,
                    source_id, raw_message_id)
                values (?, ?, ?, ?, ?::transaction_kind, ?::transaction_direction,
                        ?, ?, ?, ?, ?, ?, ?, ?, coalesce(?, false), coalesce(?, false), ?, ?, ?)
                returning id
                """,
                UUID.class,
                userId,
                request.accountId(),
                categoryId,
                merchantId,
                kind.dbValue(),
                direction.dbValue(),
                request.amount(),
                request.currencyOrDefault(),
                // base_amount equals amount until multi-currency lands; fx_rate
                // defaults to 1, so reports already read the right column.
                request.amount(),
                java.sql.Timestamp.from(request.occurredAt()),
                request.description(),
                request.notes(),
                request.tagsOrEmpty(),
                request.externalRefOrNull(),
                request.isExcluded(),
                request.isRecurring(),
                origin.importBatchId(),
                origin.sourceId(),
                origin.rawMessageId());
    }

    /** Falls back to the merchant's remembered category when none was given. */
    private UUID resolveCategory(UUID userId, UUID requested, UUID merchantId) {
        if (requested != null) {
            requireCategoryOwned(userId, requested);
            return requested;
        }
        return merchantId == null ? null : merchants.defaultCategory(userId, merchantId).orElse(null);
    }

    @Transactional
    public TransactionView update(UUID userId, UUID id, TransactionRequest request) {
        TransactionView existing = get(userId, id);
        if (TransactionKind.TRANSFER.dbValue().equals(existing.kind())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "Edit a transfer through its transfer endpoint so both legs stay in step.");
        }

        TransactionKind kind = request.resolvedKind();
        TransactionDirection direction = request.resolvedDirection();

        if (request.accountId() != null) {
            accounts.requireOwned(userId, request.accountId());
        }
        if (request.categoryId() != null) {
            requireCategoryOwned(userId, request.categoryId());
        }

        UUID merchantId = merchants.resolve(userId, request.merchant()).orElse(null);

        int updated = jdbc.update("""
                update transactions
                   set account_id = ?, category_id = ?, merchant_id = ?,
                       kind = ?::transaction_kind, direction = ?::transaction_direction,
                       amount = ?, currency = ?, base_amount = ?,
                       occurred_at = ?, description = ?, notes = ?, tags = ?,
                       external_ref = ?,
                       is_excluded = coalesce(?, is_excluded),
                       is_recurring = coalesce(?, is_recurring)
                 where user_id = ? and id = ? and deleted_at is null
                """,
                request.accountId(),
                request.categoryId(),
                merchantId,
                kind.dbValue(),
                direction.dbValue(),
                request.amount(),
                request.currencyOrDefault(),
                request.amount(),
                java.sql.Timestamp.from(request.occurredAt()),
                request.description(),
                request.notes(),
                request.tagsOrEmpty(),
                request.externalRefOrNull(),
                request.isExcluded(),
                request.isRecurring(),
                userId,
                id);

        if (updated == 0) {
            throw notFound();
        }

        merchants.rememberCategory(userId, merchantId, request.categoryId());
        return get(userId, id);
    }

    /**
     * Soft delete. Financial records stay recoverable, and a deleted row still
     * blocks its bank reference from being re-imported as a "new" expense only
     * while it lives, so the partial unique index deliberately ignores it.
     */
    @Transactional
    public void delete(UUID userId, UUID id) {
        TransactionView existing = get(userId, id);

        // A transfer with one leg deleted would silently unbalance both
        // accounts, so both legs go together.
        int deleted = existing.transferId() == null
                ? jdbc.update("""
                        update transactions set deleted_at = now()
                        where user_id = ? and id = ? and deleted_at is null
                        """, userId, id)
                : jdbc.update("""
                        update transactions set deleted_at = now()
                        where user_id = ? and transfer_id = ? and deleted_at is null
                        """, userId, existing.transferId());

        if (deleted == 0) {
            throw notFound();
        }
    }

    /**
     * Records a transfer as two legs sharing a {@code transfer_id}.
     *
     * <p>Both inserts run in one transaction: a half-written transfer would
     * show money leaving one account and never arriving at the other.
     */
    @Transactional
    public List<TransactionView> createTransfer(UUID userId, TransferRequest request) {
        if (request.fromAccountId().equals(request.toAccountId())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "Source and destination accounts must be different.");
        }
        accounts.requireOwned(userId, request.fromAccountId());
        accounts.requireOwned(userId, request.toAccountId());

        UUID transferId = UUID.randomUUID();
        UUID debitId = insertTransferLeg(userId, request, transferId,
                request.fromAccountId(), TransactionDirection.DEBIT);
        UUID creditId = insertTransferLeg(userId, request, transferId,
                request.toAccountId(), TransactionDirection.CREDIT);

        return List.of(get(userId, debitId), get(userId, creditId));
    }

    private UUID insertTransferLeg(UUID userId, TransferRequest request, UUID transferId,
            UUID accountId, TransactionDirection direction) {
        return jdbc.queryForObject("""
                insert into transactions (
                    user_id, account_id, kind, direction, amount, currency, base_amount,
                    occurred_at, description, notes, transfer_id)
                values (?, ?, 'transfer'::transaction_kind, ?::transaction_direction,
                        ?, ?, ?, ?, ?, ?, ?)
                returning id
                """,
                UUID.class,
                userId,
                accountId,
                direction.dbValue(),
                request.amount(),
                request.currencyOrDefault(),
                request.amount(),
                java.sql.Timestamp.from(request.occurredAt()),
                request.descriptionOrDefault(),
                request.notes(),
                transferId);
    }

    private void requireCategoryOwned(UUID userId, UUID categoryId) {
        Long count = jdbc.queryForObject(
                "select count(*) from categories where user_id = ? and id = ?",
                Long.class, userId, categoryId);
        if (count == null || count == 0) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Category not found");
        }
    }

    private static TransactionView mapRow(ResultSet rs, int rowNum) throws SQLException {
        return new TransactionView(
                rs.getObject("id", UUID.class),
                rs.getString("kind"),
                rs.getString("direction"),
                rs.getBigDecimal("amount"),
                rs.getBigDecimal("signed_amount"),
                rs.getString("currency"),
                rs.getTimestamp("occurred_at").toInstant(),
                rs.getString("description"),
                rs.getString("notes"),
                readTags(rs),
                rs.getObject("account_id", UUID.class),
                rs.getString("account_name"),
                rs.getObject("category_id", UUID.class),
                rs.getString("category_name"),
                rs.getObject("merchant_id", UUID.class),
                rs.getString("merchant_name"),
                rs.getObject("transfer_id", UUID.class),
                rs.getObject("counterpart_account_id", UUID.class),
                rs.getString("counterpart_account_name"),
                rs.getString("external_ref"),
                rs.getObject("merged_into_id", UUID.class),
                rs.getString("source"),
                rs.getBoolean("is_excluded"),
                rs.getBoolean("is_recurring"),
                rs.getTimestamp("created_at").toInstant());
    }

    /** Postgres arrays may contain nulls, which {@code List.of} rejects. */
    private static List<String> readTags(ResultSet rs) throws SQLException {
        Array array = rs.getArray("tags");
        if (array == null) {
            return List.of();
        }
        String[] values = (String[]) array.getArray();
        return Arrays.stream(values).filter(Objects::nonNull).toList();
    }

    private static ResponseStatusException notFound() {
        return new ResponseStatusException(HttpStatus.NOT_FOUND, "Transaction not found");
    }

    /** A page of results plus the totals for the whole filtered set. */
    public record Page(
            List<TransactionView> items,
            long total,
            BigDecimal netAmount,
            int limit,
            int offset) {

        public boolean hasMore() {
            return offset + items.size() < total;
        }
    }
}
